# Generated by Django 3.0.3 on 2020-07-26 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200726_1601'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
